apps/commons/urls.py
from django.urls import path
from .views import (HomeView, CustomerRegisterView, OwnerRegisterView, OwnerLoginView, SystemAdminLoginView,
                    SystemAdminHomeView, UserLogoutView, AddCSRView, CSRLoginView, CSRHomeView, CSRPasswordUpdateView,
                    AddBoothManagerView, AddBoothView, BoothManagerLoginView, BoothManagerAddBikeView,
                    BoothManagerHomeView, BoothManagerPasswordUpdateView, BoothManagerAddCarView, CustomerLoginView,
                    MakeLicensedCustomerView, MakeReservationRequestView, ListPendingLicenseRequestView,
                    CSRCustomerDetailView, ManageLicenseRequestView, make_reserv_request, CustomerAllReservView,
                    BoothManagerListReserveRequestView, ProcessReservationRequestView,
                    BoothManagerListAllReserveRequestView, SearchReservationRequestView, ShowResultView,
                    BoothManagerReturnReserveVehicleView, OwnerHomeView)

app_name = 'commons'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('logout/', UserLogoutView.as_view(), name="logout"),
    #################################################################################
    #                           Customer Part
    path('cust-signup/', CustomerRegisterView.as_view(), name="cust_signup"),
    path('cust-signin/', CustomerLoginView.as_view(), name="cust_signin"),
    path('cust-req-licensed/<int:pk>/', MakeLicensedCustomerView.as_view(), name="cust-req-licensed"),
    path('cust-req-reserv/<int:vid>/', MakeReservationRequestView.as_view(), name="cust-req-reserv"),
    path('req-reserv/<int:vid>/', make_reserv_request, name="cust-f-req-reserv"),
    path('cust-view-all-reserv/', CustomerAllReservView.as_view(), name="cust-view-all-reserv"),

    ###########################################################################
    #                   Vehicle Owner Part
    path('owner-signup/', OwnerRegisterView.as_view(), name='owner_signup'),
    path('owner-signin/', OwnerLoginView.as_view(), name='owner_signin'),
    path('owner/home/', OwnerHomeView.as_view(), name="owner-home"),

    ############################################################################
    #                   System Admin Part
    path('sys/', SystemAdminLoginView.as_view(), name="admin-signin"),
    path('sys/home/', SystemAdminHomeView.as_view(), name="admin-home"),
    path('sys/add-csr/', AddCSRView.as_view(), name="admin-add-csr"),

    ######################################################################3
    #                   CSR Part
    path('csr/', CSRLoginView.as_view(), name="csr-signin"),
    path('csr/home/', CSRHomeView.as_view(), name="csr-home"),
    path('csr/pwd-update/<int:pk>/', CSRPasswordUpdateView.as_view(), name="csr-pwd-update"),
    path('csr/booth-mngr/add/', AddBoothManagerView.as_view(), name="csr-add-bmngr"),
    path('csr/booth/add/', AddBoothView.as_view(), name="csr-add-booth"),
    path('csr/list-lic-req/', ListPendingLicenseRequestView.as_view(), name="csr-list-lic-req"),
    path('csr/cust-detail/<int:pk>/', CSRCustomerDetailView.as_view(), name="csr-cust-detail"),
    path('csr/manage-lic-req/<int:cid>/', ManageLicenseRequestView.as_view(), name="csr-manage-lic-req"),

    ###########################################################################
    #           Booth Manager Part
    path('bmgr/', BoothManagerLoginView.as_view(), name="bmgr-signin"),
    path('bmgr/home/', BoothManagerHomeView.as_view(), name="bmgr-home"),
    path('bmgr/pwd-update/<int:pk>/', BoothManagerPasswordUpdateView.as_view(), name="bmgr-pwd-update"),
    path('bmgr/add/bike/', BoothManagerAddBikeView.as_view(), name="bmgr-add-bike"),
    path('bmgr/add/car/', BoothManagerAddCarView.as_view(), name="bmgr-add-car"),
    path('bmgr/list-reserv-req/', BoothManagerListReserveRequestView.as_view(), name="bmgr-list-reserv-req"),
    path('bmgr/proces-reserv-req/<int:req_id>/', ProcessReservationRequestView.as_view(),
         name="bmgr-proces-reserv-req"),
    path('bmgr/all-reserv-req/', BoothManagerListAllReserveRequestView.as_view(), name="bmgr-all-reserv-req"),
    path('bmgr/search-reserv-req/', SearchReservationRequestView.as_view(), name="bmgr-search-reserv-req"),
    path('bmgr/view-reserv-req/<int:reserv_id>/', ShowResultView.as_view(), name="bmgr-view-reserv-req"),
    path('bmgr/return-reserv-veh/<int:reserv_id>/', BoothManagerReturnReserveVehicleView.as_view(),
         name="bmgr-return-reserv-veh"),

]

vehicleRenting/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.commons.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/customer/list_all_reserv.html
{% extends 'base.html' %}

{% block title %}
    Reserve List
{% endblock title %}

{% block main %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4 m-5">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">All Completed Reservation</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Reserve ID</th>
                            <th>Borrow Date</th>
                            <th>Return Date</th>
                            <th>Vehicle Taken</th>
                            <th>Taken from</th>
                            <th>Returned To</th>
                            <th>Inital Payment</th>
                            <th>Fine</th>
                            <th>Total</th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for reserv in reservation_list %}
                            <tr>
                                <td class="text-dark font-weight-bold">#RESERV_{{ reserv.id }}</td>
                                <td>{{ reserv.borrow_date }}</td>
                                {% if reserv.return_approver %}
                                <td>{{ reserv.return_date }}</td>
                                {% else %}
                                    <td>
                                        {{ reserv.expected_return_date }}<br>
                                        Expected
                                    </td>
                                {% endif %}
                                <td>
                                    <span class="text-dark font-weight-bold">{{ reserv.reservation_request.vehicle }}</span><br>
                                    {{ reserv.reservation_request.vehicle.brand }}
                                </td>
                                <td>{{ reserv.borrow_approver.booth.name }}</td>
                                <td>{{ reserv.return_approver.booth.name }}</td>
                                <td>{{ reserv.pre_payment }}</td>
                                <td class="text-danger font-weight-bolder">{{ reserv.fine }}</td>
                                <td class="text-primary font-weight-bolder">{{ reserv.total }}</td>

                            </tr>
                        {% empty %}
                            <tr>
                                <span class="text-danger font-weight-bolder">No Reservation Done yet</span>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

templates/customer/req_for_licensed.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}Licensing{% endblock title %}
{% block main %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card p-4">
                <div class="d-flex flex-row align-items-end justify-content-between">
                    <div style="flex: 2">
                        <h3 class="text-primary">Licensing</h3>
                    </div>
                    <div style="flex: 1">
                        <img src="{% static 'logos/logo1.png' %}" class="img-fluid align-self-start" width="70%">
                    </div>
                </div>
                <hr>
                <div class="card-body">
                    <h6 class="text-danger">{{ error }}</h6>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary">Update</button>
                        <button class="btn btn-secondary">Cancel</button>

                </div>
            </div>
        </div>

    </div>
{% endblock main %}

templates/customer/reserve_date.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}Reserve{% endblock title %}
{% block main %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card p-4">
                <div class="d-flex flex-row align-items-end justify-content-between">
                    <div style="flex: 2">
                        <h3 class="text-primary">Reserve</h3>
                    </div>
                    <div style="flex: 1">
                        <img src="{% static 'logos/logo1.png' %}" class="img-fluid align-self-start" width="70%">
                    </div>
                </div>
                <hr>
                <div class="card-body">
                    <h6 class="text-danger">{{ error }}</h6>
                    <form action="{% url 'commons:cust-f-req-reserv' vid %}" method="POST">
                        {% csrf_token %}
                        <h6><em>You need to pay a fare to booth manager in cash</em></h6>
                        <br><br>
                        Reserving Days : <input type="number" min="1" max="2" name="period" value="2">
                        <br><br>
                        <button class="btn btn-primary" type="submit">Submit</button>
                        <a class="btn btn-secondary" href="{% url 'commons:home' %}">Cancel</a>
                </div>
            </div>
        </div>

    </div>
{% endblock main %}