apps/commons/urls.py
from django.urls import path
from .views import (HomeView, CustomerRegisterView, OwnerRegisterView, OwnerLoginView, SystemAdminLoginView,
                    SystemAdminHomeView, UserLogoutView, AddCSRView, CSRLoginView, CSRHomeView, CSRPasswordUpdateView,
                    AddBoothManagerView, AddBoothView, BoothManagerLoginView, BoothManagerAddBikeView,
                    BoothManagerHomeView, BoothManagerPasswordUpdateView, BoothManagerAddCarView, CustomerLoginView,
                    MakeLicensedCustomerView, MakeReservationRequestView, ListPendingLicenseRequestView,
                    CSRCustomerDetailView, ManageLicenseRequestView, make_reserv_request, CustomerAllReservView,
                    BoothManagerListReserveRequestView, ProcessReservationRequestView,
                    BoothManagerListAllReserveRequestView, SearchReservationRequestView, ShowResultView,
                    BoothManagerReturnReserveVehicleView, OwnerHomeView)

app_name = 'commons'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('logout/', UserLogoutView.as_view(), name="logout"),
    #################################################################################
    #                           Customer Part
    path('cust-signup/', CustomerRegisterView.as_view(), name="cust_signup"),
    path('cust-signin/', CustomerLoginView.as_view(), name="cust_signin"),
    path('cust-req-licensed/<int:pk>/', MakeLicensedCustomerView.as_view(), name="cust-req-licensed"),
    path('cust-req-reserv/<int:vid>/', MakeReservationRequestView.as_view(), name="cust-req-reserv"),
    path('req-reserv/<int:vid>/', make_reserv_request, name="cust-f-req-reserv"),
    path('cust-view-all-reserv/', CustomerAllReservView.as_view(), name="cust-view-all-reserv"),

    ###########################################################################
    #                   Vehicle Owner Part
    path('owner-signup/', OwnerRegisterView.as_view(), name='owner_signup'),
    path('owner-signin/', OwnerLoginView.as_view(), name='owner_signin'),
    path('owner/home/', OwnerHomeView.as_view(), name="owner-home"),

    ############################################################################
    #                   System Admin Part
    path('sys/', SystemAdminLoginView.as_view(), name="admin-signin"),
    path('sys/home/', SystemAdminHomeView.as_view(), name="admin-home"),
    path('sys/add-csr/', AddCSRView.as_view(), name="admin-add-csr"),

    ######################################################################3
    #                   CSR Part
    path('csr/', CSRLoginView.as_view(), name="csr-signin"),
    path('csr/home/', CSRHomeView.as_view(), name="csr-home"),
    path('csr/pwd-update/<int:pk>/', CSRPasswordUpdateView.as_view(), name="csr-pwd-update"),
    path('csr/booth-mngr/add/', AddBoothManagerView.as_view(), name="csr-add-bmngr"),
    path('csr/booth/add/', AddBoothView.as_view(), name="csr-add-booth"),
    path('csr/list-lic-req/', ListPendingLicenseRequestView.as_view(), name="csr-list-lic-req"),
    path('csr/cust-detail/<int:pk>/', CSRCustomerDetailView.as_view(), name="csr-cust-detail"),
    path('csr/manage-lic-req/<int:cid>/', ManageLicenseRequestView.as_view(), name="csr-manage-lic-req"),

    ###########################################################################
    #           Booth Manager Part
    path('bmgr/', BoothManagerLoginView.as_view(), name="bmgr-signin"),
    path('bmgr/home/', BoothManagerHomeView.as_view(), name="bmgr-home"),
    path('bmgr/pwd-update/<int:pk>/', BoothManagerPasswordUpdateView.as_view(), name="bmgr-pwd-update"),
    path('bmgr/add/bike/', BoothManagerAddBikeView.as_view(), name="bmgr-add-bike"),
    path('bmgr/add/car/', BoothManagerAddCarView.as_view(), name="bmgr-add-car"),
    path('bmgr/list-reserv-req/', BoothManagerListReserveRequestView.as_view(), name="bmgr-list-reserv-req"),
    path('bmgr/proces-reserv-req/<int:req_id>/', ProcessReservationRequestView.as_view(),
         name="bmgr-proces-reserv-req"),
    path('bmgr/all-reserv-req/', BoothManagerListAllReserveRequestView.as_view(), name="bmgr-all-reserv-req"),
    path('bmgr/search-reserv-req/', SearchReservationRequestView.as_view(), name="bmgr-search-reserv-req"),
    path('bmgr/view-reserv-req/<int:reserv_id>/', ShowResultView.as_view(), name="bmgr-view-reserv-req"),
    path('bmgr/return-reserv-veh/<int:reserv_id>/', BoothManagerReturnReserveVehicleView.as_view(),
         name="bmgr-return-reserv-veh"),

]

vehicleRenting/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.commons.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
</head>
<body>
<!-- Start Nav Section -->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <a class="navbar-brand" href="{% url 'commons:home' %}">
        <img src="{% static 'logos/logo1.png' %}" class="img-fluid" width="120px">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if not request.user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'commons:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commons:cust_signup' %}">Customer Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commons:owner_signup' %}">Owner Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commons:cust_signin' %}">
                        LogIn
                        <i class="fas fa-sign-in-alt"></i>
                    </a>
                </li>
            {% elif request.user.customer %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'commons:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-user"></i>
                        {{ request.user.customer }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commons:cust-view-all-reserv' %}">
                       <i class="fas fa-glasses"></i>
                        View All Reserves
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commons:logout' %}">
                        Logout  <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
                <!-- Nav Item - Notifications -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle btn btn-sm btn-outline-light border-0" href="#"
                       id="alertsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {#                    <i class="fas fa-bell fa-fw"></i>#}
                        Notification <span
                            class="badge badge-info badge-counter">{{ notifications_count }}</span>
                        <!-- Counter - Alerts -->
                    </a>
                    <!-- Dropdown - Notifications -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="alertsDropdown" style="margin-right: -500px;">
                        <h6 class="dropdown-header">
                            Alerts Center
                        </h6>
                        {% for notification in notifications %}
                            <a class="dropdown-item d-flex align-items-center" href="#">
                                <div>
                            <span class="font-weight-bold">
                                {{ notification.message }} #Notif_{{ notification.id }}
                            </span>
                                </div>
                            </a>
                        {% endfor %}

                        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                    </div>
                </li>

            {% endif %}
        </ul>

    </div>
</nav>
<!-- End of Nav Section -->

<main>
    {% block main %}

    {% endblock main %}
</main>

<!-- Js -->
<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

<!-- Page level plugins -->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

{% block js %}
{% endblock js %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block main %}
    <div class="container-fluid align-center" style="height: 400px">
        <div class="row">
            <div class="col-md-6 mx-auto mt-3">
                <img src="{% static 'img/banner.gif' %}" alt="car-picture" class="img-fluid"
                     style="border-radius: 10px; border: 1px solid gray;">
            </div>
        </div>
    </div>
    <h4 class="text-dark font-weight-bolder text-center">Rent and Ride It takes no time...</h4>
    <hr>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <!-- List of Available Vehicles -->
                <ul class="list-group">
                    <li class="list-group-item text-center text-primary font-weight-bold">Available Vehicles</li>
                    {% for vehicle in available_vehicles %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ vehicle.name }}
                            <span class="badge bg-primary rounded-pill text-white">{{ vehicle.count }}</span>
                        </li>
                    {% empty %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            No Vehicles Available
                            <span class="badge rounded-pill bg-danger">0</span>
                        </li>
                    {% endfor %}
                </ul>
                <!-- End of list of Available Vehicles-->
            </div>
            <div class="col-md-10">
                <div class="row">
                    {# start of vehicle card slide show #}
                    {% for vehicle in vehicle_lists %}
                        <div class="col-md-4">
                            <div class="card">
                                <img src="{% if vehicle.bike %}
                                            {{ vehicle.bike.image.url }}
                                           {% else %}
                                            {{ vehicle.car.image.url }}
                                           {% endif %}"
                                     alt="..." class="img-fluid">
                                <div class="card-body">
                                    <h5 class="card-title"></h5>
                                    <p class="card-text">
                                        {% if vehicle.bike %}
                                            {{ vehicle.bike.type }}
                                        {% else %}
                                            {{ vehicle.car.type }}
                                        {% endif %}
                                        <br>
                                        Brand : {{ vehicle.brand }} <br>
                                        Fare : <i class='fas fa-rupee-sign text-danger'></i> {{ vehicle.fare }} per day
                                        <br>
                                        Manufacturing Year : <i
                                            class="far fa-calendar-alt"></i> {{ vehicle.manufacturing_year }} <br>
                                        Residing Booth : <i
                                            class="fas fa-map-marker-alt"></i> {{ vehicle.residing_booth.address }} <br>
                                        Booth : <i
                                            class="fas fa-map-marker-alt"></i> {{ vehicle.residing_booth.name }} <br>
                                        Mileage : <i class="fas fa-tachometer-alt"></i> {{ vehicle.mileage }} kmpl<br>
                                        Plate No. : <i class="far fa-keyboard"></i> {{ vehicle.plate_num }} <br>
                                    </p>

                                    <a href="{% url 'commons:cust-req-reserv' vehicle.id %}"
                                       class="btn btn-sm btn-primary">Request To Reserve</a>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <p class="text-black-50 display-4">No Vehicles. Call System Administrator.</p>
                    {% endfor %}
                    {# end of vehicle card slide show #}
                </div>

            </div>
        </div>
    </div>
{% endblock main %}